import { Geist, Geist_Mono, Rubik, Work_Sans } from "next/font/google";
import Navbar from "./components/Navbar";
import ProductList from "./products/ProductList";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const rubik = Rubik({
  subsets: ["latin"],
  variable: '--font-rubik'
});
const WorkSans = Work_Sans({
  subsets: ['latin'],
  variable: "--font-work-sans"
})

export const metadata = {
  title: {
    default: "Next App | My Website ",
    template: "%s | Next Website"
  },
  description: "Generated by create next app",
  keywords: ["Next js", "React js ", "Best Course on the youtube ",],
  icons: {
    icon: 'https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png'
  },

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${WorkSans.variable} ${rubik.variable} antialiased`}
      >
        
        <Navbar />
        {children}
        <ProductList/>
      </body>
    </html>
  );
}
