import { Geist, Geist_Mono,Rubik,Work_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); 
const rubik = Rubik({
  subsets:["latin"],
  variable:'--font-rubik'
});
const WorkSans=Work_Sans({
  subsets:['latin'],
  variable:"--font-work-sans"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${WorkSans.variable} ${rubik.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
